version: "3"
services:
  backend:
    container_name: backend-prod
    image: back_prod:build_${BUILD_NUMBER}
    build:
      context: .
      args:
        - WAR_FILE=target/lab-backend.war
        - CONTEXT=lab-backend
    networks:
      - prod_net_back
      - prod_net_front
    #ports:
    #  - 9998:8080

  frontend:
    container_name: frontend-prod
    image: front_prod:build_${BUILD_NUMBER}
    build:
        context: .
        args:
          - WAR_FILE=frontend/target/tasks.war
          - CONTEXT=tasks
    networks:
      - prod_net_front
    ports:
      - 9999:8080
    depends_on:
      - backend